### ISSUE TITLE
Help me, Thanks!

### ISSUE THREAD

**Issue by lovedan0928** [owowagency/swiftui-router#17]
How to call it correctly and always report the error of routerlink needs to be used in a router context. Can you give a demo?

**Comment by lovedan0928** [comment]
Then, Before you are able to use your defined routes, you need to initialise a router. Because `Router` is a protocol, multiple implementations (including your own) are possible. SwiftUI Router provides the `UINavigationControllerRouter` implementation.

Where to instantiate?

**Comment by Joannis** [comment]
@lovedan0928 there's an iOS implementation available using `UINavigationController` called `RouterView` which is a drop-in replacement.

Use it like so:

```swift
var body: some View {
    RouterView(root: myRoute)
}
```

MacOS and a SwiftUI NavigationView support are in a PR, to be reviewed by @Obbut in #9 and #15

`myRoute` is a Route definition such as this: https://github.com/owowagency/swiftui-router#-basic-routing

You can also define a route as a function with variables like so: https://github.com/owowagency/swiftui-router#parameterized-and-custom-routes

These variables can be a Binding as well.
